#!/usr/bin/env perl

use strict;
use warnings;
use autodie qw( :all );

use lib 'lib', 'inc';

use FindBin;
use R2::DatabaseManager;
use Storable qw( nfreeze );

my $db_name = $ENV{JENKINS_URL}
    || $ENV{HUDSON_URL} ? "R2Jenkins_$ENV{BUILD_NUMBER}" : 'R2Test';

R2::DatabaseManager->new(
    db_name          => $db_name,
    drop             => 1,
    seed             => 0,
    quiet            => 1,
    _existing_config => {},         # XXX - uber hack!
)->update_or_install_db();

require R2::Config;

R2::Config->instance()->_set_database_name($db_name);

my $storable = R2::Config->instance()->cache_dir()->file('R2.schema.storable');
unlink $storable if -f $storable;

# Simply loading R2::Schema should cause a storable file to be written
require R2::Schema;
